// SPDX-License-Identifier: BlueOak-1.0.0
// SPDX-FileCopyrightText: 2023 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras
// SPDX-FileCopyrightText: 2024 Saulius Krasuckas <saulius.krasuckas_at_stud_vilniustech_lt>

= Multipath TCP tyrimas duomenų centruose

Sauliaus Krasucko baigiamasis magistro darbas. +
VILNIUS TECH Elektronikos fakultetas, grupė TETfm-22

Darbo vadovas: Arūnas Statkus, VILNIUS TECH +
Darbo konsultantas: Arūnas Šaltis (anksčiau dirbęs VGTU)

=== Pristatymas

Repozitorija skirta kurti ir saugoti baigiamojo darbo

* dokumentams,
* tyrimo įrankiams
* ir rezultatams.

=== Licencija

Darbas pateikiamas atviru pavidalu, pritaikius link:LICENSE.asciidoc[Blue Oak Model License] (versija 1.0.0) –
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html[šiuolaikinį MIT licencijos pakaitalą].

Tikimasi, kad šią licenciją bus patogu skaityti tiek IT pasaulio darbuotojams, tiek ir
https://writing.kemitchell.com/living/Types-of-Lawyers.html#transactional-lawyers[intelektinės nuosavybės (IN) teisės specialistams],
dirbantiems šiose srityse:

* autorių teisių,
* prekių ženklų bei
* patentų reglamentavimo.
